### ISSUE TITLE
CommonMark changed API

### ISSUE THREAD

**Issue by defeo** [swcarpentry/lesson-example#19]
after pip-installing dependencies, `make check` fails with

```
python tools/check.py .
Traceback (most recent call last):
  File "tools/check.py", line 846, in <module>
    main(parsed_args)
  File "tools/check.py", line 831, in main
    res = validate_single(fn, template=template)
  File "tools/check.py", line 711, in validate_single
    validate_file = validator(filepath)
  File "tools/check.py", line 80, in __init__
    ast = self._parse_markdown(self.markdown)
  File "tools/check.py", line 87, in _parse_markdown
    parser = CommonMark.DocParser()
AttributeError: module 'CommonMark' has no attribute 'DocParser'
Makefile:38: recipe for target 'check' failed
make: *** [check] Error 1
```

This is because CommonMark 0.6 has [changed its API](https://pypi.python.org/pypi/CommonMark/0.6.3). Pinning down the version fixes the problem

```
$ pip install --upgrade CommonMark==0.5.5
Collecting CommonMark==0.5.5
  Using cached CommonMark-0.5.5-py2.py3-none-any.whl
Installing collected packages: CommonMark
  Found existing installation: CommonMark 0.6.3
    Uninstalling CommonMark-0.6.3:
      Successfully uninstalled CommonMark-0.6.3
Successfully installed CommonMark-0.5.5
You are using pip version 7.1.2, however version 8.0.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
$ make check 
python tools/check.py .
```

Maybe versions could be pinned down in `requirements.txt`?

**Comment by gvwilson** [comment]
Thanks Luca - we're going to do a complete overhaul of our lesson build 
system this spring, so we'll factor this one in.

**Comment by gvwilson** [comment]
We've moved to new tools.
